# This file was generated by GoReleaser. DO NOT EDIT.
class Wtf < Formula
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"
  version "0.16.0"

  if OS.mac?
    url "https://github.com/wtfutil/wtf/releases/download/v0.16.0/wtf_0.16.0_darwin_amd64.tar.gz"
    sha256 "e2065653f42228493189e41163ba908bf73d86d3a62e14724a9a78929d198af1"
  elsif OS.linux?
    url "https://github.com/wtfutil/wtf/releases/download/v0.16.0/wtf_0.16.0_linux_amd64.tar.gz"
    sha256 "27d331a9e1830b3ab6d241a89aa03c4a08e5195cd354801fdbb5d344d00b82e7"
  end

  def install
    bin.install "wtfutil"
  end
end
