# This file was generated by GoReleaser. DO NOT EDIT.
class Wtfutil < Formula
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"
  version "0.22.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wtfutil/wtf/releases/download/v0.22.0/wtf_0.22.0_darwin_amd64.tar.gz"
    sha256 "8508c8f23e2b9c97b878db8d299b0cf9aa88c0c3cc581aef2a353d5022db8d3e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wtfutil/wtf/releases/download/v0.22.0/wtf_0.22.0_linux_amd64.tar.gz"
      sha256 "73d9761f34d6b5c157bf16a11442176f03d9e1fd7595923042d87a47a2fcd53f"
    end
  end

  def install
    bin.install "wtfutil"
  end
end
