# This file was generated by GoReleaser. DO NOT EDIT.
class Wtfutil < Formula
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"
  version "0.19.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wtfutil/wtf/releases/download/v0.19.1/wtf_0.19.1_darwin_amd64.tar.gz"
    sha256 "cf017e191a5a7e7ba218eca67b30d39ee47d6480610c969218272ce76f493778"
  elsif OS.linux?
    url "https://github.com/wtfutil/wtf/releases/download/v0.19.1/wtf_0.19.1_linux_amd64.tar.gz"
    sha256 "858f47b1cd521dadb45064cc34dc314510db7a9b5d68f727cc3824087d2dcf12"
  end

  def install
    bin.install "wtfutil"
  end
end
