# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtfutil" do
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"
  version "0.45.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtfutil"

  on_macos do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v0.45.0/wtf_0.45.0_darwin_amd64.tar.gz"
      sha256 "94a9f96264133b3025b2b1306bc8f5c3e5588bc404fa9f333e39a282899876b8"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v0.45.0/wtf_0.45.0_darwin_arm64.tar.gz"
      sha256 "6a2340cc99fca57f3abb6088cdac911441248b19086f3fa72e617946fcbf08cb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v0.45.0/wtf_0.45.0_linux_amd64.tar.gz"
      sha256 "3629b7dee7a70d13db26afad82b34e8169eb867136fc25c2152d8c4f380a9eae"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v0.45.0/wtf_0.45.0_linux_arm64.tar.gz"
      sha256 "54a209ef0cc678e37004510c9707a883b391f471339c8a6a6871ac9415a577b0"
    end
  end

  conflicts_with formula: [
      "wtfutil",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
    end
  end

  # No zap stanza required
end
