# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtfutil" do
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"
  version "0.46.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtfutil"

  on_macos do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v0.46.1/wtf_0.46.1_darwin_amd64.tar.gz"
      sha256 "fb10b81bdd28b220e19227594b1c871e8cc8e64bfafc83565b8cfafbe65fd31e"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v0.46.1/wtf_0.46.1_darwin_arm64.tar.gz"
      sha256 "0732d14a2007692d501c98dafd08b05315e412d16de94bd2d4333005a4a54efa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v0.46.1/wtf_0.46.1_linux_amd64.tar.gz"
      sha256 "23d8c7952cbf6457a85e0de744cdc7c4116c24e44db7f72823722ebbb5fb230a"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v0.46.1/wtf_0.46.1_linux_arm64.tar.gz"
      sha256 "7749717b7c6dadf9cbc33cd26f1a0ba284662990bc416195640033c23a0fbf7a"
    end
  end

  conflicts_with formula: [
      "wtfutil",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
    end
  end

  # No zap stanza required
end
