# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtfutil" do
  desc "The personal information dashboard for your terminal."
  homepage "https://wtfutil.com"
  version "0.46.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtfutil"

  on_macos do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v0.46.0/wtf_0.46.0_darwin_amd64.tar.gz"
      sha256 "58123ecee7979e1dc2e3f8c090d0797a78f44d23e073c17f024c76eece1078ba"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v0.46.0/wtf_0.46.0_darwin_arm64.tar.gz"
      sha256 "970720e01766303b3b873a22d71d991d9f913c43d143e16175ac31ddeddfdf36"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wtfutil/wtf/releases/download/v0.46.0/wtf_0.46.0_linux_amd64.tar.gz"
      sha256 "cb8fbc59f6287e889d02ac1bd7c6ef7eab4c0b13c4ac56ce20d169bb49a0bb79"
    end
    on_arm do
      url "https://github.com/wtfutil/wtf/releases/download/v0.46.0/wtf_0.46.0_linux_arm64.tar.gz"
      sha256 "6f8a8a5adc28e7d6fad27939dc310b6559110ca593d51ae07d2f49bfa1e23805"
    end
  end

  conflicts_with formula: [
      "wtfutil",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtfutil"]
    end
  end

  # No zap stanza required
end
